name: 'Read package version package.json'
description: 'Output the version specified in [path]/package.json'
author: 'xile611'
inputs:
  path:
    required: false
    description: 'The directory path of target json file'
    default: './'
  filename:
    required: false
    description: 'The file name you want to read, default value is package.json'
    default: 'package.json'
  field:
    required: false
    description: 'The field which specify the version you want to read'
    default: 'version'
  use_current_version:
    required: false
    description: 'parse current version when semver_string not defined'
    default: true
  semver_string:
    required: false
    description: 'The semver string that want to be parsed'
  semver_pattern:
    required: false
    description: 'The pattern to parse the semver string'
outputs:
  version: # id of the output
    description: 'the version to read'
runs:
  using: 'node16'
  main: 'dist/index.js'
